name: DOCKER Pipeline

on:
  push:
    branches:
      - main

env:
  APP_PORT: 3000
  IMAGE_NAME: narendravarapusatya
  CONTAINER_NAME: GH-actions-practice-automatic

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:

      # 1️⃣ Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Clean
      - name: Clean Old Build
        run: rm -rf dist || true

      # 5️⃣ Build
      - name: Build Application
        run: npm run build

      # 7️⃣ Build Docker Image
      - name: Build Docker Image
        run: docker build -t rahamshaik/gabrimage:${{ github.sha }} .

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: |
             package*

      # 8️⃣ Tag Image for DockerHub
      - name: Tag Image
        run: docker tag $rahamshaik/gabrimage:${{ github.sha }} $rahamshaik/gabrimage:latest

      # 9️⃣ Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔟 Push Image
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
